### ISSUE TITLE
Todo: cose ancora da implementare nel gioco

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [everbuilds/sky-combat-application#4]
lista di cose da implementare nel gioco:

- [x] cambiare metodo di punteggio per single-player
- [x]  Il sistema permette ai giocatori presenti nella lobby di abbandonarla in qualsiasi momento prima dello scadere del clock.
- [x] La difficoltà cresce all’aumentare del punteggio della partita in maniera non lineare e può manifestarsi con l’aumento della resistenza, potenza o velocità dei NEMICI.
- [x] Le NAVICELLE NEMICHE devono differire tra di loro per la frequenza di comparsa.
- [x] Dopo che il giocatore ha azzerato la sua vita può continuare comunque a vedere i progressi dei giocatori in vita.
- [x] Deve essere fornito il piano di TEST di unità.

Da confermare con il proponente

- [x] La partita termina in modo autonomo quando rimane un solo giocatore in vita.
