### ISSUE TITLE
Todo per RQ

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [everbuilds/sky-combat-application#6]
todo di cose da fare per RQ:
- [x] (Samuele) pulsante uscita partita multiplayer
- [x] documentazione metodi
- [x] checkstyle
- [x] test unità
- [x] Git. Actions
- [x] settings (opzionale)
- [x] musica di sottofondo (opzionale)
- [x] effetti sonori (opzionale)

Potenzialmente:
- [x] non far entrare armi come power up che siano già l'arma usata dal player
